// src/services/report-export.service.ts
// Multi-format export service for reports

import * as ExcelJS from 'exceljs';
import { Readable, Transform } from 'stream';
import { Parser } from 'json2csv';
import PDFDocument from 'pdfkit';
import * as docx from 'docx';
import PresentationLayout, { PptxGenJS } from 'pptxgenjs';

interface ExportOptions {
  reportName: string;
  academicYear?: string;
  department?: string;
  generatedDate?: Date;
  generatedBy?: string;
  includeCharts?: boolean;
  logoUrl?: string;
}

interface ReportData {
  metadata: Record<string, any>;
  data: any[];
  summary?: Record<string, any>;
  charts?: Record<string, any>;
}

// ============================================================================
// EXCEL EXPORT
// ============================================================================

/**
 * Export report to Excel format with multiple sheets
 */
export async function exportToExcel(
  reportData: ReportData,
  options: ExportOptions
): Promise<Buffer> {
  try {
    const workbook = new ExcelJS.Workbook();

    // Sheet 1: Summary
    const summarySheet = workbook.addWorksheet('Summary');
    summarySheet.columns = [
      { header: 'Property', key: 'property', width: 25 },
      { header: 'Value', key: 'value', width: 40 },
    ];

    // Add metadata
    summarySheet.addRows([
      { property: 'Report Name', value: options.reportName },
      { property: 'Generated Date', value: new Date().toLocaleDateString() },
      { property: 'Generated By', value: options.generatedBy || 'System' },
      { property: 'Academic Year', value: options.academicYear || 'N/A' },
      { property: 'Department', value: options.department || 'All' },
      { property: '', value: '' },
    ]);

    // Add summary statistics
    if (reportData.summary) {
      Object.entries(reportData.summary).forEach(([key, value]) => {
        summarySheet.addRow({
          property: key,
          value: typeof value === 'object' ? JSON.stringify(value) : value,
        });
      });
    }

    // Format summary sheet
    summarySheet.getRow(1).font = { bold: true, size: 12 };
    summarySheet.getRow(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF4472C4' } };
    summarySheet.getRow(1).font = { bold: true, color: { argb: 'FFFFFFFF' } };

    // Sheet 2: Data
    if (reportData.data && reportData.data.length > 0) {
      const dataSheet = workbook.addWorksheet('Data');
      const columns = Object.keys(reportData.data[0]);

      dataSheet.columns = columns.map(col => ({
        header: col.charAt(0).toUpperCase() + col.slice(1),
        key: col,
        width: 15,
      }));

      // Add data rows
      reportData.data.forEach(row => {
        dataSheet.addRow(row);
      });

      // Format header row
      dataSheet.getRow(1).font = { bold: true };
      dataSheet.getRow(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFD9E1F2' } };

      // Auto-fit columns
      dataSheet.columns.forEach(col => {
        col.width = Math.min(col.width || 15, 50);
      });

      // Add alternating row colors
      dataSheet.eachRow((row, rowNumber) => {
        if (rowNumber > 1 && rowNumber % 2 === 0) {
          row.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF2F2F2' } };
        }
      });
    }

    // Sheet 3: Charts data (if available)
    if (reportData.charts && Object.keys(reportData.charts).length > 0) {
      const chartsSheet = workbook.addWorksheet('Charts');
      chartsSheet.columns = [
        { header: 'Chart Name', key: 'chartName', width: 25 },
        { header: 'Data', key: 'data', width: 50 },
      ];

      Object.entries(reportData.charts).forEach(([name, data]) => {
        chartsSheet.addRow({
          chartName: name,
          data: JSON.stringify(data),
        });
      });
    }

    // Generate buffer
    const buffer = await workbook.xlsx.writeBuffer();
    return buffer as Buffer;
  } catch (error) {
    console.error('Error exporting to Excel:', error);
    throw new Error(`Excel export failed: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}

// ============================================================================
// CSV EXPORT
// ============================================================================

/**
 * Export report to CSV format
 */
export async function exportToCSV(
  reportData: ReportData,
  options: ExportOptions
): Promise<string> {
  try {
    if (!reportData.data || reportData.data.length === 0) {
      return 'No data to export';
    }

    const parser = new Parser({
      fields: Object.keys(reportData.data[0]),
      header: true,
    });

    const csv = parser.parse(reportData.data);
    
    // Add header comments
    const header = [
      `Report Name: ${options.reportName}`,
      `Generated Date: ${new Date().toLocaleDateString()}`,
      `Generated By: ${options.generatedBy || 'System'}`,
      `Academic Year: ${options.academicYear || 'N/A'}`,
      '',
    ].join('\n');

    return header + csv;
  } catch (error) {
    console.error('Error exporting to CSV:', error);
    throw new Error(`CSV export failed: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}

// ============================================================================
// PDF EXPORT
// ============================================================================

/**
 * Export report to PDF format
 */
export async function exportToPDF(
  reportData: ReportData,
  options: ExportOptions
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: 'A4',
        margin: 50,
      });

      const chunks: Buffer[] = [];

      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // Title
      doc.fontSize(24).font('Helvetica-Bold').text(options.reportName, { align: 'center' });
      doc.moveDown(0.5);

      // Metadata
      doc.fontSize(10).font('Helvetica').fillColor('#666666');
      doc.text(`Generated on: ${new Date().toLocaleString()}`, { align: 'center' });
      doc.text(`Academic Year: ${options.academicYear || 'N/A'}`, { align: 'center' });
      doc.text(`Department: ${options.department || 'All Departments'}`, { align: 'center' });
      doc.moveDown(1);

      // Divider line
      doc.strokeColor('#CCCCCC').lineWidth(1).moveTo(50, doc.y).lineTo(545, doc.y).stroke();
      doc.moveDown(0.5);

      // Summary Section
      if (reportData.summary) {
        doc.fontSize(14).font('Helvetica-Bold').fillColor('#000000').text('Summary', { underline: true });
        doc.moveDown(0.3);

        Object.entries(reportData.summary).forEach(([key, value]) => {
          doc.fontSize(10).font('Helvetica');
          if (typeof value === 'object') {
            doc.text(`${key}: ${JSON.stringify(value)}`);
          } else {
            doc.text(`${key}: ${value}`);
          }
        });

        doc.moveDown(0.5);
      }

      // Data Table
      if (reportData.data && reportData.data.length > 0) {
        doc.fontSize(14).font('Helvetica-Bold').fillColor('#000000').text('Data', { underline: true });
        doc.moveDown(0.3);

        // Table headers
        const columns = Object.keys(reportData.data[0]);
        const columnWidth = 500 / columns.length;

        doc.fontSize(9).font('Helvetica-Bold').fillColor('#FFFFFF');
        doc.rect(50, doc.y, 500, 20).fill('#4472C4');
        columns.forEach((col, idx) => {
          doc.text(
            col.substring(0, 15),
            50 + idx * columnWidth,
            doc.y - 17,
            { width: columnWidth - 5, align: 'left' }
          );
        });

        doc.moveDown(1.2);

        // Table rows (limit to first 50 rows for PDF size)
        doc.fontSize(8).font('Helvetica').fillColor('#000000');
        const rowsToShow = Math.min(reportData.data.length, 50);

        reportData.data.slice(0, rowsToShow).forEach((row, idx) => {
          if (doc.y > 750) {
            doc.addPage();
          }

          const rowColor = idx % 2 === 0 ? '#F2F2F2' : '#FFFFFF';
          doc.rect(50, doc.y, 500, 15).fill(rowColor);
          doc.fillColor('#000000');

          columns.forEach((col, colIdx) => {
            const value = String(row[col] || '').substring(0, 20);
            doc.text(
              value,
              50 + colIdx * columnWidth,
              doc.y - 12,
              { width: columnWidth - 5, align: 'left' }
            );
          });

          doc.moveDown(1.2);
        });

        if (reportData.data.length > rowsToShow) {
          doc.fontSize(9).fillColor('#FF0000')
            .text(`... and ${reportData.data.length - rowsToShow} more records (see Excel export for full data)`);
        }
      }

      // Footer
      doc.moveDown(1);
      doc.fontSize(8).fillColor('#999999').text(
        `Page ${doc.bufferedPageRange().count}`,
        { align: 'center' }
      );

      doc.end();
    } catch (error) {
      reject(new Error(`PDF export failed: ${error instanceof Error ? error.message : 'Unknown error'}`));
    }
  });
}

// ============================================================================
// WORD EXPORT
// ============================================================================

/**
 * Export report to Word (.docx) format
 */
export async function exportToWord(
  reportData: ReportData,
  options: ExportOptions
): Promise<Buffer> {
  try {
    const sections = [];

    // Title and metadata section
    sections.push(
      new docx.Paragraph({
        text: options.reportName,
        heading: docx.HeadingLevel.HEADING_1,
        alignment: docx.AlignmentType.CENTER,
        spacing: { after: 200 },
        style: 'Title',
      }),
      new docx.Paragraph({
        text: `Generated on: ${new Date().toLocaleString()}`,
        alignment: docx.AlignmentType.CENTER,
        spacing: { after: 100 },
      }),
      new docx.Paragraph({
        text: `Academic Year: ${options.academicYear || 'N/A'}`,
        alignment: docx.AlignmentType.CENTER,
        spacing: { after: 100 },
      }),
      new docx.Paragraph({
        text: `Department: ${options.department || 'All Departments'}`,
        alignment: docx.AlignmentType.CENTER,
        spacing: { after: 400 },
      }),
      new docx.Paragraph({
        text: '',
        border: {
          bottom: {
            color: 'CCCCCC',
            space: 1,
            style: docx.BorderStyle.SINGLE,
            size: 6,
          },
        },
      })
    );

    // Summary section
    if (reportData.summary && Object.keys(reportData.summary).length > 0) {
      sections.push(
        new docx.Paragraph({
          text: 'Summary',
          heading: docx.HeadingLevel.HEADING_2,
          spacing: { before: 200, after: 200 },
        })
      );

      Object.entries(reportData.summary).forEach(([key, value]) => {
        sections.push(
          new docx.Paragraph({
            text: `${key}: ${typeof value === 'object' ? JSON.stringify(value, null, 2) : value}`,
            spacing: { after: 100 },
          })
        );
      });

      sections.push(new docx.Paragraph({ text: '', spacing: { after: 200 } }));
    }

    // Data table section
    if (reportData.data && reportData.data.length > 0) {
      sections.push(
        new docx.Paragraph({
          text: 'Detailed Report Data',
          heading: docx.HeadingLevel.HEADING_2,
          spacing: { before: 200, after: 200 },
        })
      );

      const columns = Object.keys(reportData.data[0]);
      const tableRows = [
        new docx.TableRow({
          cells: columns.map(
            col =>
              new docx.TableCell({
                children: [
                  new docx.Paragraph({
                    text: col,
                    bold: true,
                    color: 'FFFFFF',
                  }),
                ],
                shading: { fill: '4472C4', type: 'clear' },
              })
          ),
        }),
      ];

      // Add data rows (limit to 100 rows to avoid huge documents)
      reportData.data.slice(0, 100).forEach((row, idx) => {
        tableRows.push(
          new docx.TableRow({
            cells: columns.map(
              col =>
                new docx.TableCell({
                  children: [
                    new docx.Paragraph({
                      text: String(row[col] || ''),
                    }),
                  ],
                  shading: {
                    fill: idx % 2 === 0 ? 'F2F2F2' : 'FFFFFF',
                    type: 'clear',
                  },
                })
            ),
          })
        );
      });

      sections.push(
        new docx.Table({
          rows: tableRows,
          width: { size: 100, type: docx.WidthType.PERCENTAGE },
        })
      );

      if (reportData.data.length > 100) {
        sections.push(
          new docx.Paragraph({
            text: `\n... and ${reportData.data.length - 100} more records (see Excel export for full data)`,
            italics: true,
            color: 'FF0000',
            spacing: { before: 200 },
          })
        );
      }
    }

    // Signature section
    sections.push(
      new docx.Paragraph({ text: '', spacing: { before: 400 } }),
      new docx.Paragraph({
        text: 'Generated by Mathematics Dashboard System',
        alignment: docx.AlignmentType.CENTER,
        color: '999999',
        spacing: { before: 200 },
      })
    );

    const doc = new docx.Document({
      sections: [
        {
          properties: {},
          children: sections,
        },
      ],
    });

    const buffer = await docx.Packer.toBuffer(doc);
    return buffer;
  } catch (error) {
    console.error('Error exporting to Word:', error);
    throw new Error(`Word export failed: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}

// ============================================================================
// POWERPOINT EXPORT
// ============================================================================

/**
 * Export report to PowerPoint (.pptx) format
 */
export async function exportToPPT(
  reportData: ReportData,
  options: ExportOptions
): Promise<Buffer> {
  try {
    const pres = new PptxGenJS();
    pres.defineLayout({ name: 'TITLE_SLIDE', master: 'BLANK' });

    // Slide 1: Title Slide
    let slide = pres.addSlide();
    slide.background = { color: '4472C4' };
    slide.addText(options.reportName, {
      x: 0.5,
      y: 2,
      w: 9,
      h: 2,
      fontSize: 44,
      bold: true,
      color: 'FFFFFF',
      align: 'center',
    });
    slide.addText(`Academic Year: ${options.academicYear || 'N/A'}`, {
      x: 0.5,
      y: 4.5,
      w: 9,
      h: 0.8,
      fontSize: 18,
      color: 'FFFFFF',
      align: 'center',
    });
    slide.addText(`Generated on: ${new Date().toLocaleDateString()}`, {
      x: 0.5,
      y: 5.5,
      w: 9,
      h: 0.6,
      fontSize: 14,
      color: 'D9E1F2',
      align: 'center',
    });

    // Slide 2: Summary
    if (reportData.summary && Object.keys(reportData.summary).length > 0) {
      slide = pres.addSlide();
      slide.addText('Summary', {
        x: 0.5,
        y: 0.5,
        w: 9,
        fontSize: 32,
        bold: true,
        color: '4472C4',
      });

      const summaryItems = Object.entries(reportData.summary).map(([key, value]) => [
        key,
        typeof value === 'object' ? JSON.stringify(value) : String(value),
      ]);

      slide.addTable(summaryItems, {
        x: 0.5,
        y: 1.5,
        w: 9,
        colW: [3, 6],
        border: { pt: 1, color: 'CCCCCC' },
        fill: { color: 'F2F2F2' },
        rowH: 0.5,
        fontSize: 12,
      });
    }

    // Slide 3: Key Observations (if data available)
    if (reportData.data && reportData.data.length > 0) {
      slide = pres.addSlide();
      slide.addText('Key Observations', {
        x: 0.5,
        y: 0.5,
        w: 9,
        fontSize: 32,
        bold: true,
        color: '4472C4',
      });

      const observations = [
        `Total Records: ${reportData.data.length}`,
        `Report Type: ${reportData.metadata.reportType || 'General'}`,
        `Generated By: ${options.generatedBy || 'System'}`,
        `Department: ${options.department || 'All Departments'}`,
      ];

      observations.forEach((obs, idx) => {
        slide.addText(obs, {
          x: 1,
          y: 1.5 + idx * 0.8,
          w: 8.5,
          fontSize: 14,
          bullet: true,
        });
      });
    }

    // Slide 4: Data Sample (first 10 records)
    if (reportData.data && reportData.data.length > 0) {
      slide = pres.addSlide();
      slide.addText('Data Sample', {
        x: 0.5,
        y: 0.5,
        w: 9,
        fontSize: 32,
        bold: true,
        color: '4472C4',
      });

      const columns = Object.keys(reportData.data[0]).slice(0, 4); // Limit to 4 columns
      const tableData = [columns];

      reportData.data.slice(0, 10).forEach(row => {
        tableData.push(columns.map(col => String(row[col] || '')));
      });

      slide.addTable(tableData, {
        x: 0.5,
        y: 1.5,
        w: 9,
        colW: [2.25, 2.25, 2.25, 2.25],
        border: { pt: 1, color: 'CCCCCC' },
        fill: { color: 'D9E1F2' },
        rowH: 0.4,
        fontSize: 10,
      });

      if (reportData.data.length > 10) {
        slide.addText(`... and ${reportData.data.length - 10} more records`, {
          x: 0.5,
          y: 6.5,
          w: 9,
          fontSize: 12,
          italics: true,
          color: 'FF0000',
        });
      }
    }

    // Slide 5: Conclusion
    slide = pres.addSlide();
    slide.addText('Conclusion', {
      x: 0.5,
      y: 0.5,
      w: 9,
      fontSize: 32,
      bold: true,
      color: '4472C4',
    });
    slide.addText(
      'This report has been generated by the Mathematics Dashboard System. For detailed analysis and filtering, please refer to the Excel export.',
      {
        x: 1,
        y: 2,
        w: 8,
        fontSize: 14,
        align: 'center',
      }
    );

    const buffer = await pres.write({ outputType: 'arraybuffer' });
    return Buffer.from(buffer);
  } catch (error) {
    console.error('Error exporting to PPT:', error);
    throw new Error(`PowerPoint export failed: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}

// ============================================================================
// Export utilities
// ============================================================================

export const ReportExportService = {
  exportToExcel,
  exportToCSV,
  exportToPDF,
  exportToWord,
  exportToPPT,
};

export default ReportExportService;
